-- StationeryPro schema. Run in Supabase SQL Editor on a NEW project.
-- Keep the anon/publishable key in frontend. NEVER put service_role key in browser code.
create extension if not exists pgcrypto;

create type public.app_role as enum ('owner','employee','developer');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'New User',
  role public.app_role not null default 'employee',
  active boolean not null default true,
  permissions text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sku text unique,
  category text,
  unit text not null default 'pcs',
  cost_price numeric(14,2) not null default 0 check(cost_price >= 0),
  selling_price numeric(14,2) not null default 0 check(selling_price >= 0),
  stock_qty numeric(14,3) not null default 0 check(stock_qty >= 0),
  reorder_level numeric(14,3) not null default 5 check(reorder_level >= 0),
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  receipt_no bigint generated by default as identity unique,
  cashier_id uuid not null references public.profiles(id),
  total_amount numeric(14,2) not null check(total_amount >= 0),
  payment_method text not null check(payment_method in ('cash','mobile_money','card','credit','mixed')),
  payment_status text not null default 'paid' check(payment_status in ('paid','partial','unpaid')),
  status text not null default 'completed' check(status in ('completed','void','refunded')),
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id),
  product_id uuid references public.products(id),
  product_name text not null,
  quantity numeric(14,3) not null check(quantity > 0),
  unit_price numeric(14,2) not null check(unit_price >= 0),
  unit_cost numeric(14,2) not null default 0 check(unit_cost >= 0),
  line_total numeric(14,2) not null check(line_total >= 0)
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id),
  quantity_change numeric(14,3) not null,
  reason text not null,
  reference_id uuid,
  actor_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null default 'Nyingine',
  amount numeric(14,2) not null check(amount > 0),
  notes text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id integer primary key default 1 check(id=1),
  business_name text not null default 'Stationery',
  phone text,
  address text,
  receipt_footer text,
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);
insert into public.business_settings(id,business_name) values(1,'Stationery') on conflict(id) do nothing;

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create or replace function public.current_role()
returns public.app_role
language sql stable security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and active = true
$$;

create or replace function public.has_permission(required_permission text)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and active = true
    and (role in ('owner','developer') or required_permission = any(permissions))
  )
$$;

-- Automatically create a basic employee profile on auth signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name, role)
  values(new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)), 'employee')
  on conflict(id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Product creation + initial stock is one transaction.
create or replace function public.create_product_with_stock(
  p_name text, p_sku text, p_category text, p_unit text,
  p_cost_price numeric, p_selling_price numeric, p_stock_qty numeric, p_reorder_level numeric
) returns uuid language plpgsql security definer set search_path=public
as $$
declare new_id uuid;
begin
  if not public.has_permission('products.manage') then raise exception 'Huna ruhusa ya kusajili bidhaa'; end if;
  if p_name is null or length(trim(p_name))=0 then raise exception 'Jina la bidhaa linahitajika'; end if;
  if p_cost_price < 0 or p_selling_price < 0 or p_stock_qty < 0 or p_reorder_level < 0 then raise exception 'Thamani haiwezi kuwa hasi'; end if;
  insert into public.products(name,sku,category,unit,cost_price,selling_price,stock_qty,reorder_level,created_by)
  values(trim(p_name),nullif(trim(p_sku),''),nullif(trim(p_category),''),coalesce(nullif(trim(p_unit),''),'pcs'),p_cost_price,p_selling_price,p_stock_qty,p_reorder_level,auth.uid())
  returning id into new_id;
  if p_stock_qty > 0 then
    insert into public.stock_movements(product_id,quantity_change,reason,actor_id)
    values(new_id,p_stock_qty,'Opening stock',auth.uid());
  end if;
  insert into public.audit_logs(actor_id,action,entity_type,entity_id,details)
  values(auth.uid(),'create','product',new_id::text,jsonb_build_object('name',p_name,'opening_stock',p_stock_qty));
  return new_id;
end;
$$;

create or replace function public.adjust_stock(p_product_id uuid,p_quantity numeric,p_reason text)
returns void language plpgsql security definer set search_path=public
as $$
begin
  if not public.has_permission('products.manage') then raise exception 'Huna ruhusa ya kubadilisha stock'; end if;
  if p_quantity <= 0 then raise exception 'Quantity lazima iwe zaidi ya sifuri'; end if;
  if p_reason is null or length(trim(p_reason))=0 then raise exception 'Sababu inahitajika'; end if;
  update public.products set stock_qty=stock_qty+p_quantity,updated_at=now() where id=p_product_id and active=true;
  if not found then raise exception 'Bidhaa haijapatikana'; end if;
  insert into public.stock_movements(product_id,quantity_change,reason,actor_id)
  values(p_product_id,p_quantity,trim(p_reason),auth.uid());
  insert into public.audit_logs(actor_id,action,entity_type,entity_id,details)
  values(auth.uid(),'stock_in','product',p_product_id::text,jsonb_build_object('quantity',p_quantity,'reason',p_reason));
end;
$$;

-- Atomic sale: checks prices/stock from database, then updates stock + writes receipt/items.
create or replace function public.create_sale(p_items jsonb,p_payment_method text,p_total_amount numeric)
returns uuid language plpgsql security definer set search_path=public
as $$
declare new_sale_id uuid; item jsonb; prod public.products%rowtype; qty numeric; price numeric; computed_total numeric:=0; supplied_product uuid;
begin
  if auth.uid() is null or public.current_role() is null then raise exception 'Login inahitajika'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Hakuna bidhaa kwenye mauzo'; end if;
  if p_payment_method not in ('cash','mobile_money','card','credit','mixed') then raise exception 'Njia ya malipo si sahihi'; end if;
  -- Validate the full cart before inserting anything.
  for item in select * from jsonb_array_elements(p_items) loop
    supplied_product := (item->>'product_id')::uuid;
    qty := (item->>'quantity')::numeric;
    if qty <= 0 then raise exception 'Quantity si sahihi'; end if;
    select * into prod from public.products where id=supplied_product and active=true for update;
    if not found then raise exception 'Bidhaa haipo tena'; end if;
    if prod.stock_qty < qty then raise exception 'Stock haitoshi kwa bidhaa: %',prod.name; end if;
    price := prod.selling_price;
    computed_total := computed_total + qty*price;
  end loop;
  if abs(computed_total-p_total_amount) > 0.01 then raise exception 'Jumla imebadilika. Refresh bidhaa na ujaribu tena.'; end if;
  insert into public.sales(cashier_id,total_amount,payment_method,payment_status)
  values(auth.uid(),computed_total,p_payment_method,case when p_payment_method='credit' then 'unpaid' else 'paid' end)
  returning id into new_sale_id;
  for item in select * from jsonb_array_elements(p_items) loop
    supplied_product := (item->>'product_id')::uuid;
    qty := (item->>'quantity')::numeric;
    select * into prod from public.products where id=supplied_product and active=true for update;
    price := prod.selling_price;
    insert into public.sale_items(sale_id,product_id,product_name,quantity,unit_price,unit_cost,line_total)
    values(new_sale_id,prod.id,prod.name,qty,price,prod.cost_price,qty*price);
    update public.products set stock_qty=stock_qty-qty,updated_at=now() where id=prod.id;
    insert into public.stock_movements(product_id,quantity_change,reason,reference_id,actor_id)
    values(prod.id,-qty,'Sale',new_sale_id,auth.uid());
  end loop;
  insert into public.audit_logs(actor_id,action,entity_type,entity_id,details)
  values(auth.uid(),'create','sale',new_sale_id::text,jsonb_build_object('total',computed_total,'payment_method',p_payment_method));
  return new_sale_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.expenses enable row level security;
alter table public.business_settings enable row level security;
alter table public.audit_logs enable row level security;

-- Profile list for owner/developer; users may see own profile.
create policy "profiles read own or managers" on public.profiles for select to authenticated
using (id=auth.uid() or public.current_role() in ('owner','developer'));
create policy "profiles update managers" on public.profiles for update to authenticated
using (public.current_role() in ('owner','developer'))
with check (public.current_role() in ('owner','developer'));

create policy "products read authenticated" on public.products for select to authenticated
using (public.current_role() is not null);
create policy "products update managers" on public.products for update to authenticated
using (public.has_permission('products.manage'))
with check (public.has_permission('products.manage'));
create policy "products insert managers" on public.products for insert to authenticated
with check (public.has_permission('products.manage'));
create policy "sales read managers or own" on public.sales for select to authenticated
using (public.current_role() in ('owner','developer') or cashier_id=auth.uid());
create policy "sale items read managers or own" on public.sale_items for select to authenticated
using (exists(select 1 from public.sales s where s.id=sale_id and (s.cashier_id=auth.uid() or public.current_role() in ('owner','developer'))));
create policy "stock movement read managers" on public.stock_movements for select to authenticated
using (public.current_role() in ('owner','developer'));
create policy "expenses read managers" on public.expenses for select to authenticated
using (public.current_role() in ('owner','developer') or public.has_permission('expenses.view'));
create policy "expenses insert permitted" on public.expenses for insert to authenticated
with check (public.has_permission('expenses.manage'));
create policy "settings read authenticated" on public.business_settings for select to authenticated
using (public.current_role() is not null);
create policy "settings update managers" on public.business_settings for update to authenticated
using (public.current_role() in ('owner','developer'))
with check (public.current_role() in ('owner','developer'));
create policy "settings insert managers" on public.business_settings for insert to authenticated
with check (public.current_role() in ('owner','developer'));
create policy "audit read managers" on public.audit_logs for select to authenticated
using (public.current_role() in ('owner','developer'));

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update on public.products to authenticated;
grant select on public.sales, public.sale_items, public.stock_movements to authenticated;
grant select, insert on public.expenses to authenticated;
grant select, insert, update on public.business_settings to authenticated;
grant select on public.audit_logs to authenticated;
grant execute on function public.create_sale(jsonb,text,numeric) to authenticated;
grant execute on function public.create_product_with_stock(text,text,text,text,numeric,numeric,numeric,numeric) to authenticated;
grant execute on function public.adjust_stock(uuid,numeric,text) to authenticated;

-- IMPORTANT: first owner setup instructions are in README.md.
